const CARDS = [
 {
  "title": "Mostar Guide",
  "cat": "Travel",
  "premium": false,
  "poster": "assets/cards/card-00.webp",
  "video": "assets/videos/card-00.mp4",
  "auto": false,
  "slug": "mostar-guide",
  "free": true,
  "likes": 82,
  "creator": "@AmirMushich",
  "promptFile": "prompts/mostar-guide.md"
 },
 {
  "title": "Personal Showcase",
  "cat": "Portfolio",
  "premium": false,
  "poster": "assets/cards/card-01.webp",
  "video": "assets/videos/card-01.mp4",
  "auto": false,
  "slug": "personal-showcase",
  "free": true,
  "likes": 55,
  "creator": null,
  "promptFile": "prompts/personal-showcase.md"
 },
 {
  "title": "OYLA",
  "cat": "Ecommerce",
  "premium": true,
  "poster": "assets/cards/card-02.webp",
  "video": "assets/cards/oyla-video.mp4",
  "auto": false,
  "slug": "oyla",
  "free": false,
  "likes": 261,
  "creator": null
 },
 {
  "title": "3D Portfolio",
  "cat": "Portfolio",
  "premium": false,
  "poster": "assets/cards/card-03.webp",
  "video": "assets/videos/card-03.mp4",
  "auto": false,
  "slug": "3d-jack-portfolio-hero",
  "free": true,
  "likes": 1114,
  "creator": null,
  "promptFile": "prompts/3d-jack-portfolio-hero.md"
 },
 {
  "title": "Sentinel",
  "cat": "Cybersecurity",
  "premium": true,
  "poster": "assets/cards/card-04.webp",
  "video": "assets/videos/card-04.mp4",
  "auto": false,
  "slug": "sentinel",
  "free": false,
  "likes": 71,
  "creator": "seanaiux"
 },
 {
  "title": "Data Storytelling",
  "cat": "SaaS",
  "premium": true,
  "poster": "assets/cards/card-05.webp",
  "video": "assets/videos/card-05.mp4",
  "auto": false,
  "slug": "data-storytelling",
  "free": false,
  "likes": 62,
  "creator": "seanaiux"
 },
 {
  "title": "Dreamcore Landing",
  "cat": "Landing Page",
  "premium": true,
  "poster": "assets/cards/card-06.webp",
  "video": null,
  "auto": false,
  "slug": "dreamcore-landing",
  "free": false,
  "likes": 343,
  "creator": null
 },
 {
  "title": "Build Unit",
  "cat": "Agency",
  "premium": true,
  "poster": "assets/cards/card-07.webp",
  "video": "assets/videos/card-07.mp4",
  "auto": false,
  "slug": "build-unit",
  "free": false,
  "likes": 3,
  "creator": null
 },
 {
  "title": "Bold Studio",
  "cat": "Hero",
  "premium": false,
  "poster": "assets/cards/card-08.webp",
  "video": null,
  "auto": false,
  "slug": "bold-studio",
  "free": true,
  "likes": 290,
  "creator": null,
  "promptFile": "prompts/bold-studio.md"
 },
 {
  "title": "Breathstone",
  "cat": "Wellness",
  "premium": true,
  "poster": "assets/cards/card-09.webp",
  "video": "assets/videos/card-09.mp4",
  "auto": false,
  "slug": "breathstone",
  "free": false,
  "likes": 3,
  "creator": null
 },
 {
  "title": "Prisma Creative Studio",
  "cat": "Landing Page",
  "premium": false,
  "poster": "assets/cards/card-10.gif",
  "video": null,
  "auto": true,
  "slug": "prisma-landing",
  "free": true,
  "likes": 560,
  "creator": null,
  "promptFile": "prompts/prisma-landing.md"
 },
 {
  "title": "Creator Guild",
  "cat": "Community",
  "premium": true,
  "poster": "assets/cards/card-11.webp",
  "video": "assets/videos/card-11.mp4",
  "auto": false,
  "slug": "creator-guild",
  "free": false,
  "likes": 7,
  "creator": null
 },
 {
  "title": "Interactive Discovery",
  "cat": "Hero",
  "premium": false,
  "poster": "assets/cards/card-12.webp",
  "video": null,
  "auto": false,
  "slug": "interactive-discovery",
  "free": true,
  "likes": 560,
  "creator": "seanaiux",
  "promptFile": "prompts/interactive-discovery.md"
 },
 {
  "title": "Silent Velocity",
  "cat": "Technology",
  "premium": true,
  "poster": "assets/cards/card-13.webp",
  "video": "assets/videos/card-13.mp4",
  "auto": false,
  "slug": "silent-velocity",
  "free": false,
  "likes": 9,
  "creator": null
 },
 {
  "title": "Synth Mode",
  "cat": "Fashion",
  "premium": false,
  "poster": "assets/cards/card-14.webp",
  "video": "assets/videos/card-14.mp4",
  "auto": false,
  "slug": "synth-mode",
  "free": true,
  "likes": 28,
  "creator": null,
  "promptFile": "prompts/synth-mode.md"
 },
 {
  "title": "Art Landing",
  "cat": "Landing Page",
  "premium": true,
  "poster": "assets/cards/card-15.jpg",
  "video": "assets/videos/card-15.mp4",
  "auto": false,
  "slug": "art-landing",
  "free": false,
  "likes": 212,
  "creator": null
 },
 {
  "title": "Agent Crew",
  "cat": "AI",
  "premium": true,
  "poster": "assets/cards/card-16.webp",
  "video": "assets/videos/card-16.mp4",
  "auto": false,
  "slug": "agent-crew",
  "free": false,
  "likes": 20,
  "creator": "@elayadesigns"
 },
 {
  "title": "Velorah",
  "cat": "Agency",
  "premium": false,
  "poster": "assets/cards/card-17.gif",
  "video": null,
  "auto": false,
  "slug": "velorah-hero",
  "free": true,
  "likes": 511,
  "creator": null,
  "promptFile": "prompts/velorah-hero.md"
 },
 {
  "title": "Skybridge 404",
  "cat": "404",
  "premium": false,
  "poster": "assets/cards/card-18.webp",
  "video": "assets/videos/card-18.mp4",
  "auto": false,
  "slug": "skybridge-404",
  "free": true,
  "likes": 25,
  "creator": "@elayadesigns",
  "promptFile": "prompts/skybridge-404.md"
 },
 {
  "title": "Web3 EOS Hero",
  "cat": "Web3",
  "premium": true,
  "poster": "assets/cards/card-19.png",
  "video": null,
  "auto": false,
  "slug": "9",
  "free": false,
  "likes": 183,
  "creator": null
 },
 {
  "title": "Aetheris Voyage",
  "cat": "Hero Section",
  "premium": false,
  "poster": "assets/cards/card-20.gif",
  "video": null,
  "auto": false,
  "slug": "aetheris-voyage-hero",
  "free": true,
  "likes": 590,
  "creator": null,
  "promptFile": "prompts/aetheris-voyage-hero.md"
 },
 {
  "title": "Intelligent Operations",
  "cat": "Agency",
  "premium": false,
  "poster": "assets/cards/card-21.webp",
  "video": "assets/videos/card-21.mp4",
  "auto": false,
  "slug": "intelligent-operations",
  "free": true,
  "likes": 51,
  "creator": null,
  "promptFile": "prompts/intelligent-operations.md"
 },
 {
  "title": "CoderCrest",
  "cat": "SaaS",
  "premium": true,
  "poster": "assets/cards/card-22.gif",
  "video": null,
  "auto": false,
  "slug": "codercrest-hero",
  "free": false,
  "likes": 91,
  "creator": null
 },
 {
  "title": "Augmented Sight",
  "cat": "Technology",
  "premium": true,
  "poster": "assets/cards/card-23.webp",
  "video": "assets/videos/card-23.mp4",
  "auto": false,
  "slug": "augmented-sight",
  "free": false,
  "likes": 11,
  "creator": null
 },
 {
  "title": "VEX Ventures",
  "cat": "Hero Section",
  "premium": false,
  "poster": "assets/cards/card-24.gif",
  "video": null,
  "auto": false,
  "slug": "vex-ventures-hero",
  "free": true,
  "likes": 398,
  "creator": null,
  "promptFile": "prompts/vex-ventures-hero.md"
 },
 {
  "title": "Cloud Kicks",
  "cat": "Fashion",
  "premium": true,
  "poster": "assets/cards/card-25.webp",
  "video": "assets/videos/card-25.mp4",
  "auto": false,
  "slug": "cloud-kicks",
  "free": false,
  "likes": 16,
  "creator": null
 },
 {
  "title": "SkyElite Private Jets",
  "cat": "Landing Page",
  "premium": false,
  "poster": "assets/cards/card-26.gif",
  "video": null,
  "auto": false,
  "slug": "skyelite-hero",
  "free": true,
  "likes": 240,
  "creator": null,
  "promptFile": "prompts/skyelite-hero.md"
 },
 {
  "title": "Urban Jungle",
  "cat": "Landing Page",
  "premium": true,
  "poster": "assets/cards/card-27.webp",
  "video": "assets/videos/card-27.mp4",
  "auto": false,
  "slug": "urban-jungle-hero",
  "free": false,
  "likes": 268,
  "creator": null
 },
 {
  "title": "Routine Coach",
  "cat": "Wellness",
  "premium": true,
  "poster": "assets/cards/card-28.webp",
  "video": "assets/videos/card-28.mp4",
  "auto": false,
  "slug": "routine-coach",
  "free": false,
  "likes": 22,
  "creator": null
 },
 {
  "title": "Reveal Hero",
  "cat": "Hero",
  "premium": true,
  "poster": "assets/cards/card-29.webp",
  "video": null,
  "auto": false,
  "slug": "reveal-hero",
  "free": false,
  "likes": 161,
  "creator": null
 },
 {
  "title": "TrustFlow",
  "cat": "Finance",
  "premium": false,
  "poster": "assets/cards/card-30.webp",
  "video": "assets/videos/card-30.mp4",
  "auto": false,
  "slug": "trustflow",
  "free": true,
  "likes": 65,
  "creator": null,
  "promptFile": "prompts/trustflow.md"
 },
 {
  "title": "Modern Agency",
  "cat": "Agency",
  "premium": false,
  "poster": "assets/cards/card-31.webp",
  "video": null,
  "auto": true,
  "slug": "modern-agency",
  "free": true,
  "likes": 268,
  "creator": null,
  "promptFile": "prompts/modern-agency.md"
 },
 {
  "title": "Relocation Card",
  "cat": "Finance",
  "premium": true,
  "poster": "assets/cards/card-32.webp",
  "video": "assets/videos/card-32.mp4",
  "auto": false,
  "slug": "relocation-card",
  "free": false,
  "likes": 51,
  "creator": "seanaiux"
 },
 {
  "title": "Liquid Glass Agency",
  "cat": "Landing Page",
  "premium": true,
  "poster": "assets/cards/card-33.gif",
  "video": null,
  "auto": true,
  "slug": "liquid-glass-agency",
  "free": false,
  "likes": 151,
  "creator": null
 },
 {
  "title": "Form Study",
  "cat": "Art",
  "premium": true,
  "poster": "assets/cards/card-34.webp",
  "video": "assets/videos/card-34.mp4",
  "auto": false,
  "slug": "form-study",
  "free": false,
  "likes": 35,
  "creator": null
 },
 {
  "title": "Luxury Ecommerce Design",
  "cat": "Landing Page",
  "premium": true,
  "poster": "assets/cards/card-35.webp",
  "video": null,
  "auto": true,
  "slug": "luxury-editorial-ecommerce-design",
  "free": false,
  "likes": 158,
  "creator": null
 },
 {
  "title": "Digital Director",
  "cat": "Portfolio",
  "premium": false,
  "poster": "assets/cards/card-36.webp",
  "video": "assets/videos/card-36.mp4",
  "auto": false,
  "slug": "digital-director",
  "free": true,
  "likes": 46,
  "creator": null,
  "promptFile": "prompts/digital-director.md"
 },
 {
  "title": "Grow AI Talent Platform",
  "cat": "SaaS",
  "premium": true,
  "poster": "assets/cards/card-37.gif",
  "video": null,
  "auto": false,
  "slug": "grow-ai-hero",
  "free": false,
  "likes": 71,
  "creator": null
 },
 {
  "title": "Custom Spaces",
  "cat": "Design",
  "premium": true,
  "poster": "assets/cards/card-38.webp",
  "video": "assets/videos/card-38.mp4",
  "auto": false,
  "slug": "custom-spaces",
  "free": false,
  "likes": 60,
  "creator": null
 },
 {
  "title": "Aethera Studio",
  "cat": "Hero Section",
  "premium": false,
  "poster": "assets/cards/card-39.gif",
  "video": null,
  "auto": false,
  "slug": "aethera-hero",
  "free": true,
  "likes": 407,
  "creator": null,
  "promptFile": "prompts/aethera-hero.md"
 },
 {
  "title": "Glassmorphism Agency Hero",
  "cat": "Agency",
  "premium": true,
  "poster": "assets/cards/card-40.gif",
  "video": null,
  "auto": false,
  "slug": "5",
  "free": false,
  "likes": 60,
  "creator": null
 },
 {
  "title": "Arctic Lab",
  "cat": "Portfolio",
  "premium": true,
  "poster": "assets/cards/card-41.webp",
  "video": "assets/videos/card-41.mp4",
  "auto": false,
  "slug": "arctic-lab",
  "free": false,
  "likes": 19,
  "creator": null
 },
 {
  "title": "Asme",
  "cat": "Hero Section",
  "premium": false,
  "poster": "assets/cards/card-42.gif",
  "video": null,
  "auto": false,
  "slug": "asme-hero",
  "free": true,
  "likes": 422,
  "creator": null,
  "promptFile": "prompts/asme-hero.md"
 },
 {
  "title": "Avant Studio",
  "cat": "Creative",
  "premium": true,
  "poster": "assets/cards/card-43.webp",
  "video": "assets/videos/card-43.mp4",
  "auto": false,
  "slug": "avant-studio",
  "free": false,
  "likes": 36,
  "creator": null
 },
 {
  "title": "Logoisum Video Agency Hero",
  "cat": "Agency",
  "premium": true,
  "poster": "assets/cards/card-44.gif",
  "video": null,
  "auto": false,
  "slug": "14",
  "free": false,
  "likes": 68,
  "creator": null
 },
 {
  "title": "Editorial Eyewear",
  "cat": "Fashion",
  "premium": true,
  "poster": "assets/cards/card-45.webp",
  "video": "assets/videos/card-45.mp4",
  "auto": false,
  "slug": "editorial-eyewear",
  "free": false,
  "likes": 37,
  "creator": null
 },
 {
  "title": "Innovation",
  "cat": "Landing Page",
  "premium": false,
  "poster": "assets/cards/card-46.gif",
  "video": null,
  "auto": true,
  "slug": "innovation-landing",
  "free": true,
  "likes": 409,
  "creator": null,
  "promptFile": "prompts/innovation-landing.md"
 },
 {
  "title": "Remote Dev Collective",
  "cat": "Agency Website",
  "premium": true,
  "poster": "assets/cards/card-47.webp",
  "video": "assets/videos/card-47.mp4",
  "auto": false,
  "slug": "remote-dev-collective",
  "free": false,
  "likes": 23,
  "creator": "seanaiux"
 }
];
